<?php
// Only for post request
if ( $_SERVER['REQUEST_METHOD'] != 'POST' ) {
	die();
}

// Include the config file
require_once( dirname( __FILE__ ) . '/config.php' );

// Kill if this is the demo site
if ( defined( 'IPTDEMO' ) && true == IPTDEMO ) {
	?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<strong>Demo Only</strong> Saving modifications has been disabled in this demo. Please download and host it yourself.
</div>
	<?php
	die();
}

// Get the JSON file
$icm_json = json_decode( file_get_contents( ABSPATH . ICMPATH . 'selection.json' ), true );

// Get class prefix
$class_prefix = $icm_json['preferences']['fontPref']['prefix'];
unset( $icm_json );

// Init the variables
$new_icon_code = array();
$categories = array();
$images = array();

// Loop through configuration and populate the category variable
foreach ( $icon_categories as $preset_icons ) {
	$categories[$preset_icons['id']] = array(
		'id' => $preset_icons['id'],
		'label' => $preset_icons['label'],
		'elements' => array(),
		'element_classes' => array(),
		'tags' => isset( $preset_icons['tags'] ) ? $preset_icons['tags'] : array(),
	);
}

// Fetch and clean the post variable
$post = (array) @$_POST['icon'];
if ( get_magic_quotes_gpc() ) {
	array_walk_recursive( $post, 'stripslashes' );
}

// Check the count
$post_count = count($post);

// Index the POST data
foreach ( $post as $icon ) {
	$cat_key = $icon['cat'];
	if ( isset( $categories[$cat_key] ) ) {
		$icon_key = hexdec($icon['hex_code']);
		$categories[$cat_key]['elements'][$icon_key] = $icon['name'];
		$categories[$cat_key]['element_classes'][$icon_key] = $icon['class'];
		$images[$icon_key] = $icon['image'];
	}
}

$new_icon_code = array_values( $categories );
$new_count = count( $images );

// Now create the data to be saved in the iconindexed
ob_start();
?>
/**
 * The content of this file is autogenerated
 * Last Indexed: <?php echo date( 'Y-m-d H:i:s' ); ?> by the autogenerator
 *
 * IcoMoonIconIndexer Automated script by swashata <swashata@intechgrity.com>
 * @link https://github.com/swashata/IcoMoonIconIndexer GPLV3 Licensed
 */

$icomoon_indexed_last = '<?php echo date( 'Y-m-d H:i:s' ); ?>';
$icomoon_icons = array(
<?php foreach ( $new_icon_code as $icons ) : ?>
	array(
		'id' => '<?php echo $icons['id']; ?>',
		'label' => '<?php echo $icons['label']; ?>',
		'elements' => array(
<?php echo "\t\t\t"; $count = 1; foreach ( $icons['elements'] as $ic_key => $ic ) : ?>0x<?php echo dechex( $ic_key ); ?> => '<?php echo addslashes($ic); ?>', <?php if ( $count % 6 == 0 ) echo "\n\t\t\t"; else echo ' '; ?>
<?php $count++; endforeach; ?>

		),
		'element_classes' => array(
<?php echo "\t\t\t"; $count = 1; foreach ( $icons['element_classes'] as $ic_key => $ic ) : ?>0x<?php echo dechex( $ic_key ); ?> => '<?php echo addslashes( $class_prefix . $ic); ?>', <?php if ( $count % 6 == 0 ) echo "\n\t\t\t"; else echo ' '; ?>
<?php $count++; endforeach; ?>

		),
		'tags' => array(
			'<?php echo implode('\', \'', array_map('addslashes', $icons['tags'])); ?>',
		),
	),
<?php endforeach; ?>
);

$icomoon_images = array(
<?php foreach ( $images as $ic_key => $ic ) : ?>
	0x<?php echo dechex( $ic_key ); ?> => '<?php echo addslashes( $ic ); ?>',
<?php endforeach; ?>
);
<?php

// Get the new indexed values
$new_file_content = ob_get_clean();

// Write to the file
file_put_contents( ABSPATH . 'iconindexed.php', "<?php\n\n" . $new_file_content );
?>
<div class="alert alert-info">
	<strong>Success</strong> Successfully indexed and saved the data to <code>iconindexed.php</code> file.
</div>
<ul>
	<li><strong>Total Icons Posted:</strong> <?php echo $post_count; ?></li>
	<li><strong>Total Icons Indexed:</strong> <?php echo $new_count; ?></li>
</ul>
<p>
	<a href="test-icons.php" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-log-in"></span> Test Indexed Icons</a>
</p>
