<?php
/**
 * This file has some sample functions written to generate
 *  - SELECT html (for class|attribute)
 *  - JavaScript JSON files (for class|attribute) for fontIconPicker
 * etc...
 *
 * Modify them according to your need
 */

/**
 * Generate HTML SELECT OPTION along with OPTGROUP
 *
 * You will need to provide the SELECT element yourself as this only generates the optgroup and option elements
 *
 * @param  array  $icomoon_icons The original variable generated by this script
 * @param  string $by            What to print the value by. Possibilities are class, unicode, hex|hexadecimal or key
 * @return string                The optgroup and option for you to echo
 */
function imii_generate_select_options( $icomoon_icons, $by = 'class' ) {
	$return = '';
	$by = strtolower( $by );
	foreach ( $icomoon_icons as $icons ) {
		$return .= '<optgroup label="' . htmlspecialchars( $icons['label'] ) . '">';
		if ( isset( $icons['elements'] ) ) {
			foreach ( $icons['elements'] as $ic_key => $ic_name ) {
				$val = $ic_key;
				if ( $by == 'class' ) {
					$val = htmlspecialchars( $icons['element_classes'][$ic_key] );
				} else if ( $by == 'unicode' ) {
					$val = '&#x' . dechex( $ic_key ) . ';';
				} else if ( $by == 'hex' || $by == 'hexadecimal' ) {
					$val = dechex( $ic_key );
				}
				$return .= '<option value="' . $val . '">' . $ic_name . '</option>';
			}
		}
		$return .= '</optgroup>';
	}
	return $return;
}

/**
 * Generate the JSON variable for the <code>source</code> option for fontIconPicker
 *
 * You will need to assign it to a variable inside JavaScript code
 * @link https://github.com/micc83/fontIconPicker fontIconPicker Project Page
 *
 * @param  array  $icomoon_icons The original variable generated by this script
 * @param  string $by            What to print the value by. Possibilities are class or key
 * @return string                The JSON which can be assigned to a variable. See example
 */
function imii_generate_fip_source_json( $icomoon_icons, $by = 'class' ) {
	$json = array();
	$by = strtolower( $by );
	foreach ( $icomoon_icons as $icons ) {
		$icon_set = array();
		if ( isset( $icons['elements'] ) ) {
			foreach ( $icons['elements'] as $ic_key => $ic_name ) {
				$val = $ic_key;
				if ( $by == 'class' ) {
					$val = htmlspecialchars( $icons['element_classes'][$ic_key] );
				}
				$icon_set[] = $val;
			}
		}
		$json[$icons['label']] = $icon_set;
	}
	return json_encode( $json );
}

/**
 * Generate the JSON variable for the <code>searchSource</code> option for fontIconPicker
 *
 * You will need to assign it to a variable inside JavaScript code
 * @link https://github.com/micc83/fontIconPicker fontIconPicker Project Page
 *
 * @param  array  $icomoon_icons The original variable generated by this script
 * @return string                The JSON which can be assigned to a variable. See example
 */
function imii_generate_fip_search_json( $icomoon_icons ) {
	$json = array();
	foreach ( $icomoon_icons as $icons ) {
		$icon_set = array();
		if ( isset( $icons['elements'] ) ) {
			foreach ( $icons['elements'] as $ic_key => $ic_name ) {
				$icon_set[] = $ic_name;
			}
		}
		$json[$icons['label']] = $icon_set;
	}
	return json_encode( $json );
}
